name: Check if PR is actually valid

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge"

