name: Run training job in two environments

on: push

jobs:
  train-dev:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Run azure ml job
      run: |
        az ml job create -f src/job_test.yml --resource-group rg-dp100 --workspace-name mlw-tomas --stream
  train-prod:
    runs-on: ubuntu-latest
    environment: production
    needs: train-dev
    steps:
        - name: Check out repo
          uses: actions/checkout@main
        - name: Install az ml extension
          run: az extension add -n ml -y
        - name: Azure login
          uses: azure/login@v1
          with:
            creds: ${{secrets.AZURE_CREDENTIALS}}
        - name: Run azure ml job
          run: |
            az ml job create -f src/job_prod.yml --resource-group rg-dp100 --workspace-name mlw-tomas --stream


